name: Matix and if always() bug
on: [push, pull_request]

jobs:
  bug:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Matrix that runs artifact step 
            is_special: true
 
          - name: Martix two
    steps:
      - name: Fail step
        if: ${{ matrix.is_special }}
        run: exit 1
      
      - name: Upload artifacts (with true flag)
        if: ${{ matix.is_special }} 
        run: echo "Would instead use actions/aritifacts!"
      
      - name: Upload artifacts (with always)
        if: ${{ always() }} 
        run: echo "Would instead use actions/aritifacts!"
  
