name: Steps if conditional bug
on: [push, pull_request]
jobs:
  bug:
    runs-on: ubuntu-latest
    steps:
      - name: Fail step
        run: exit 1

      - name: Upload artifacts (with if true check)
        if: ${{ true }}
        run: echo "Would instead use actions/artifacts!"

      - name: Upload artifacts (with always)
        if: ${{ always() }}
        run: echo "Would instead use actions/artifacts!"

  bug_with_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Matrix that runs artifact step
            some_flag: true

    steps:
      - name: Fail step
        if: ${{ matrix.some_flag }}
        run: exit 1

      - name: Upload artifacts (with true flag)
        if: ${{ matrix.some_flag }}
        run: echo "Would instead use actions/artifacts!"

      - name: Upload artifacts (with always)
        if: ${{ always() }}
        run: echo "Would instead use actions/artifacts!"
